init:
		find . -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;
		find . -type f -name ".terraform.lock.hcl" -prune -exec rm -rf {} \;
		terragrunt run-all init
apply:
		find . -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;
		find . -type f -name ".terraform.lock.hcl" -prune -exec rm -rf {} \;
		terragrunt run-all validate
		echo "y" | terragrunt run-all apply
destroy:
		find . -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;
		find . -type f -name ".terraform.lock.hcl" -prune -exec rm -rf {} \;
		echo "y" | terragrunt run-all destroy
